### ISSUE TITLE
Singer player game not responding after a while

### ISSUE THREAD

**Issue by TreeryMAA** [starforcraft/Cable-Tiers#11]
I am playing on the latest version of ATM6 skyblock and I am experiencing "Server not responding" problem after I enter the world for a while, this only happens when I am using version 0.3 or higher cable tiers. When I try to close the game, the game is stuck on the saving phase and I can only close the game by force closing it. I guess this is due to the creative importer/exporter?

**Comment by starforcraft** [comment]
Can you send me your latest.log?

**Comment by TreeryMAA** [comment]
[latest.log](https://github.com/starforcraft/Cable-Tiers/files/6899772/latest.log)
I removed fast furnace and upgrade cable tier mod and test it out but the same problem still happened.

**Comment by starforcraft** [comment]
Could you upload it on https://pastebin.com ? Github is really buggy on phone

**Comment by TreeryMAA** [comment]
Sorry for the late reply
The log seems to repeat after this
https://pastebin.com/sVm8wJGd

**Comment by starforcraft** [comment]
The log says citadel and ice&fire and not Cable Tiers :)

**Comment by TreeryMAA** [comment]
https://pastebin.com/V5JuWsbF
I think I fixed the citadel and ice&fire problem but the "waiting for server" problem still occurs in version 0.3 or above.
Downgrading the mod fix this problem.

**Comment by starforcraft** [comment]
Hmm log doesn't says anything could you run Spark?

**Comment by TreeryMAA** [comment]
When this occurs, the game doesn't respond to anything, after I type in the command, nothing happened

**Comment by starforcraft** [comment]
Did you write it right? /spark run timeout 30

**Comment by TreeryMAA** [comment]
https://spark.lucko.me/XYv4XZoUbc
The stop responding problem occurs after about 1-2 minutes
And I set the timer to 3 minutes

**Comment by starforcraft** [comment]
Hmm it seems to be the Creative Exporter

**Comment by starforcraft** [comment]
Can you show your setup?

**Comment by TreeryMAA** [comment]
What should I show? How I am setting up the exporter? Or the whole storage system?

**Comment by starforcraft** [comment]
How you set up the Exporter

**Comment by TreeryMAA** [comment]
Two creative exporters in compact machine, one exporting ore into block placer(from Cyclic), the other one, which have crafting upgrade, is exporting ore to chemical injector(from mekanism).
And two exporters in the overworld, one exporting to an ender chest(from EnderStorage), the other is exporting to a tier 5 centrifuge.

**Comment by starforcraft** [comment]
Hmm spark says something with Storage Drawers

**Comment by TreeryMAA** [comment]
After removing the crafting upgrade, the problem seems to be fixed, the game runs fine after 5 minutes.

**Comment by starforcraft** [comment]
Hmm okay good I will have to look at that Crafting Upgrade

**Comment by TreeryMAA** [comment]
Yeah, when I put the crafting upgrade back into the exporter, the server just stop responding.

**Comment by Schweigsam83** [comment]
Hello, i can second that a crafting upgrade in an creative exporter will kill a game. Tested in a fresh blank world with a creative controller on export to an item user of cyclic. (Modpack ATM6)

**Comment by SenojLuap** [comment]
I've also reproduced the crash in the latest (1.7.9) ATM6 modpack

**Comment by starforcraft** [comment]
https://www.curseforge.com/minecraft/mc-mods/cable-tiers/files/3434705 :)
