### ISSUE TITLE
Issue with Tank Nulls

### ISSUE THREAD

**Issue by PABessero** [starforcraft/Cable-Tiers#12]
Happened in pack All The Mods 6 v1.7.7
Mod version: 0.31

A crash happens upon switching a creative importer attached to an empty Dock (from Tank Null) to fluid mode
[crash-2021-08-10_10.07.35-server.txt](https://github.com/starforcraft/Cable-Tiers/files/6963691/crash-2021-08-10_10.07.35-server.txt)
[crash-2021-08-10_10.50.47-server.txt](https://github.com/starforcraft/Cable-Tiers/files/6963693/crash-2021-08-10_10.50.47-server.txt)

**Comment by PABessero** [comment]
https://pastebin.com/hvU0trCH (ticking took 60s)
https://pastebin.com/4dfctQLU (Actual error, out of bounds)

**Comment by starforcraft** [comment]
https://github.com/starforcraft/Cable-Tiers/commit/934e75c5286a1d71c9215630846e9ee4d30953d2 :)
