### ISSUE TITLE
Requesters are not valid recipes in ATM6

### ISSUE THREAD

**Issue by AlexHailstone** [starforcraft/Cable-Tiers#15]
Hey Team,

Cable Tiers Version: cabletiers-1.16x-0.501
Mod Pack: All the Mods 6 (version 1.7.11)
Minecraft Version: 1.16.5

Issue:
No valid recipes can be used to make the upgraded requesters.

Expected Result:
When using the screenshots provided (as JEI doesn't list the recipes either)
![image](https://user-images.githubusercontent.com/76534423/132611566-e5e5ec77-bf5f-452c-bc77-414421ba3378.png)
This is the expected receipe.

![image](https://user-images.githubusercontent.com/76534423/132611682-bdbbb5e1-7d0c-4c6c-8758-939c001a1bac.png)
This is my game.

I can verify that they do not seem to fully function yet either. (or at least I cannot store integers to the amount)
![image](https://user-images.githubusercontent.com/76534423/132611929-f2ba2467-b998-4964-b672-98a70158cf09.png)
Close then reopen:
![image](https://user-images.githubusercontent.com/76534423/132611951-5ad029fc-c0b4-4ebc-8e10-c21338537c0a.png)

I'm super excited that these were in ATM6 as I thought they weren't.

**Comment by starforcraft** [comment]
This is ATM 6s fault. They fixed the Recipes in Staging Branch so I think the recipes will be fixed in 1.8.0.
