### ISSUE TITLE
Crash while trying to insert into drawer

### ISSUE THREAD

**Issue by beaussan** [starforcraft/Cable-Tiers#16]
During the initial insertion into the drawer using a ultra exporter, everything worked fine, but as soon as I extracted something from this drawer, I have the server crashing, and even after restarting the server multiple time, same crash :

https://termbin.com/eg3k

Pack : ATM 6 version 1.7.11, if this helps

Thanks !

**Comment by starforcraft** [comment]
https://www.curseforge.com/minecraft/mc-mods/cable-tiers/files/3457220 :)
