### ISSUE TITLE
Creative Importer Time Out with infinite fluid containers

### ISSUE THREAD

**Issue by AFKafe** [starforcraft/Cable-Tiers#18]
Hello,

When I connect a "Creative Importer" to a "Creative Fluid Tank" from "Mekanism" as well as to other infinite containers, such as the "Sink" from "Cooking for Blockheads" my game (or my server) switches to " Waiting for server ... "and I can't do anything about it. The only option is to use a backup.

Replication:
- Have a "Refined Storage" network
- Connect a Creative Importer to an infinite container (like the Sink from Cooking for Blockheads)

Here is my latest log: https://pastebin.com/pfddZXdp
It stops as soon as I put the Creative Importer down but does not log me out and does not cause a crash

Regards and Courage <3

**Comment by starforcraft** [comment]
Hmm I think it happens because the Creative Importer is instant so its transfering max int/t and if Minecraft goes over that Value weird things happens. But the Problem is I think I cannot do something about that. But I will look at it :)
