### ISSUE TITLE
Can't switch importer mode

### ISSUE THREAD

**Issue by Nagispace** [starforcraft/Cable-Tiers#21]
It seems I can't switch the importers to "fluid" mode.

**Comment by starforcraft** [comment]
Hmm are you playing on Server? And can you send your log?

**Comment by Nagispace** [comment]
Yes.
It does the same with everything else from cable tiers.
[latest.log](https://github.com/starforcraft/Cable-Tiers/files/7295161/latest.log)
[Uploading debug.log…]()

**Comment by ThePotato97** [comment]
When i try clicking any buttons on the left IO Mode/Type/Mode the block changes to this missing texture and connected changes to false
![image](https://user-images.githubusercontent.com/10260415/139515983-8aa3cf55-f7eb-4df8-a73f-f4c6d638bbc3.png)
![image](https://user-images.githubusercontent.com/10260415/139516018-b78752a9-af4b-4656-9c3f-e3f565fe4d9c.png)

**Comment by starforcraft** [comment]
> When i try clicking any buttons on the left IO Mode/Type/Mode the block changes to this missing texture and connected changes to false
> ![image](https://user-images.githubusercontent.com/10260415/139515983-8aa3cf55-f7eb-4df8-a73f-f4c6d638bbc3.png)
> ![image](https://user-images.githubusercontent.com/10260415/139516018-b78752a9-af4b-4656-9c3f-e3f565fe4d9c.png)

Update Cable Tiers

**Comment by starforcraft** [comment]
https://www.curseforge.com/minecraft/mc-mods/cable-tiers/files/3550712
