### ISSUE TITLE
Requestify doesnt save quantity

### ISSUE THREAD

**Issue by dualmacops** [starforcraft/Cable-Tiers#22]
Requestify tiers doesn't show the save button nor the quantity can be saved with any button.
![image](https://user-images.githubusercontent.com/9700375/137777559-a56cfa4c-330d-4370-bda4-74b99b94b973.png)

Version: cabletiers-1.16.5-0.52
Modpack: ATM6 1.8.6

**Comment by starforcraft** [comment]
> Also, pressing the "type" button changes the redstone mode to only work with redstone signal, not changing the type.

Same as above
