### ISSUE TITLE
[cabletiers-1.16.5-0.532] Requesters not working

### ISSUE THREAD

**Issue by joeltine** [starforcraft/Cable-Tiers#23]
I'm playing All the Mods 6 w/ cable tiers cabletiers-1.16.5-0.532.jar installed. None of the elite, ultra, or creative requesters will set the "inventory" value and therefore request the system to craft anything. You enter a number and it just resets to 0 when you close the UI. 

Note, the @rsrequestify requester (also installed in this mod pack) works fine.

**Comment by starforcraft** [comment]
Remove Extra Storage they somehow break them
