### ISSUE TITLE
[Bug] Crafters from ExtraStorage stop showing redstone control anymore

### ISSUE THREAD

**Issue by iammael** [starforcraft/Cable-Tiers#24]
Creating this issue following an issue on ExtraStorage : https://github.com/Edivad99/ExtraStorage/issues/29#issuecomment-850807899

Whenever Cable Tiers is in a modpack, any Crafters from ExtraStorage stop showing the ability to control them via Redstone.

**Comment by starforcraft** [comment]
https://www.curseforge.com/minecraft/mc-mods/cable-tiers/files/3550712

**Comment by iammael** [comment]
The update worked for a little while, but now for no apparent reason the Redstone control disappeared again.
