### ISSUE TITLE
Requester not retaining amount requested of an item

### ISSUE THREAD

**Issue by LolidyOG** [starforcraft/Cable-Tiers#25]
enter an amount for the pre-specified item I'd like retained, exit the requester, re-enter the requester, requesting amount has returned to 0. This is being experienced playing the "all the mods 6" modpack version 1.8.9, MC1.16.5. Not sure if there's any relation

**Comment by starforcraft** [comment]
Remove Extra Storage mod

**Comment by LolidyOG** [comment]
shoot, those two dont play well together.. Thank you.
