### ISSUE TITLE
Cover clipping bug

### ISSUE THREAD

**Issue by C4J3** [starforcraft/Cable-Tiers#26]
![2021-12-26_16 01 49](https://user-images.githubusercontent.com/13005453/147413642-efd53bb7-2724-4700-8b50-f996ada3c1d6.png)

Certain blocks like the 'structors and the importer clip into hollow covers. (Top row are RS versions and the bottom row are ultimate versions from CT. Seems to happen with all tiers of them.)

MC: 1.16.5
Forge: 36.2.22
RS: 1.9.16
Cable Tiers: 0.543
Optifine: HD U G8

**Comment by starforcraft** [comment]
https://www.curseforge.com/minecraft/mc-mods/cable-tiers/files/3601375
