### ISSUE TITLE
Multiplayer - Can't change Redstone Mode

### ISSUE THREAD

**Issue by DomenicWalther** [starforcraft/Cable-Tiers#29]
Running cabletiers-1.16.5-0.544 with the ATM 6 Modpack.
It's not possible for me to change the Redstone Mode for any Block that's been added with this mod when playing on a Multiplayer Server.

**Comment by starforcraft** [comment]
Log?

**Comment by DomenicWalther** [comment]
https://pastebin.com/6MbA3hdP

What I've just noticed is that in fact I can't change the Value of any Button when clicking on it while playing on a Server. This is me just randomly clicking the differnet options in the GUI of a Ultra Exporter & Constructor and also trying the same with a Crafter from the Extra Storage Mod.

**Comment by DragarX** [comment]
Same issue here. 
when server first starts I can change the values, but after an unknown time functionality stops.

**Comment by starforcraft** [comment]
Going to close this issue because its the same issue as #34
