### ISSUE TITLE
Item Dupe Glitch - Creative Destructor/Constructor

### ISSUE THREAD

**Issue by cdgamedev** [starforcraft/Cable-Tiers#3]
Mod Version: cabletiers-1.16x-0.24.jar

Same issue as reported here: https://github.com/AllTheMods/ATM-6/issues/1984

The issue occurs when you remove and place a block quickly using the Creative Destructor and Constructor.

Video showcase:
https://www.youtube.com/watch?v=iprCPK4pBRc

**Comment by starforcraft** [comment]
Hmm will fix after my vacation :)

**Comment by starforcraft** [comment]
Fixed in next Update :)
