### ISSUE TITLE
[1.18.1] Requester recipes missing

### ISSUE THREAD

**Issue by aerialspring** [starforcraft/Cable-Tiers#33]
In JEI, I'm only able to see a recipe for the ultra and creative requesters, but the elite requester (which shows up in the recipe for the ultra) doesn't have a recipe, and I don't even see the first one, that I'm assuming would be the basic requester. Very strange. 

Cable Tiers 0.545
Forge 39.1.0
JEI 9.4.1.11

![2022-03-13 04_59_28-Window](https://user-images.githubusercontent.com/10717721/158052472-e7eb67a0-4791-4824-a38e-dc9f7d61a6a5.png)
2

**Comment by starforcraft** [comment]
You probably don’t have rsRequestify installed lol

**Comment by aerialspring** [comment]
Oh my gosh!! *headdesk* thank you lol
