### ISSUE TITLE
Server Crash behaviour on 1.16.5 with Disk Manipulator Upgrades

### ISSUE THREAD

**Issue by KiichigoUsagi** [starforcraft/Cable-Tiers#35]
The server and client end up crashing when placing and interacting with any of the improved Disk Manipulators.

Crashlog: [https://bytebin.lucko.me/L2JLrBlHNT](url)

Minecraft Version: 1.16.5
Forge version: 36.2.33
Cable Tiers: cabletiers-1.16.5-0.5441

Modpack: The Mahogany Bunny

**Comment by starforcraft** [comment]
The crashlog link isn’t working for me

**Comment by starforcraft** [comment]
Woops nvm im stupid

**Comment by starforcraft** [comment]
Are you playing on a server?

**Comment by KiichigoUsagi** [comment]
tried on both server and singleplayer
hence my "The server and client end up crashing.."

**Comment by starforcraft** [comment]
https://www.curseforge.com/minecraft/mc-mods/cable-tiers/files/3787208
