### ISSUE TITLE
Request: Tiered Disk Manipulator

### ISSUE THREAD

**Issue by iTitus** [starforcraft/Cable-Tiers#4]
The standard disk manipulator feels slow when trying to defrag your huge 4096k drives, even when fully upgraded.
The higher tiers are faster by default and they may allow parallel processing of multiple drives or more slots for serial processing.

**Comment by starforcraft** [comment]
Actually this was in planning but I didn’t had enough time to do it so I throw the idea away but it seems like many people want it so when im back from my vacation I will make it :)

**Comment by starforcraft** [comment]
https://www.curseforge.com/minecraft/mc-mods/cable-tiers/files/3432497 :)
