### ISSUE TITLE
1.16.5 Excessive TPS consumption

### ISSUE THREAD

**Issue by Sakata-MC** [starforcraft/Cable-Tiers#40]
I placed 16 of the ultra exporters for the extra slots, to compact a build. TPS started tanking and profiler seems to show that
com.YTrollman.CableTiers.node.TieredExportNetworkNode.update() is consuming roughly 40% of all tick time.
Removing these cables does resolve the TPS lag.

With exporters:
https://spark.lucko.me/Rrqhr39JlC

Without:
https://spark.lucko.me/RfTv3hCqPe

Was exporting into loot fabricators from "Hostile Neural Networks"

**Comment by starforcraft** [comment]
Can you try this again but without the Storage Drawer connected to the System?
