### ISSUE TITLE
Game freezes and crashes when opening grid when using ultra importer with four speed upgrades on a multiservo press

### ISSUE THREAD

**Issue by DeleteMetaInf** [starforcraft/Cable-Tiers#41]
I’ve found an extremely weird and specific issue with Cable Tiers. When attaching an ultra importer with four speed upgrades to a [Thermal Series](https://www.curseforge.com/minecraft/mc-mods/thermal-expansion) multiservo press, the game, when opening the Refined Storage grid, slows down to a halt, freezes, and eventually crashes, whether it’s the wireless grid or not.

When I have this ultra importer on the multiservo press, the RAM usage spikes when opening the RS grid, and the game freezes. Oddly, when removing just one of the speed upgrades, leaving three in the ultra importer, this ceases to be an issue. Dedicating 11 GB of RAM rather than 9.5 GB didn’t help either. The game’s RAM usage is normal and as low as to be expected otherwise.

**Crash report:** https://pastebin.com/raw/NaawggDk

#### Screenshot

<details>
  <summary>Screenshot (click to expand)</summary>
  
![2022-08-19_17 49 17](https://user-images.githubusercontent.com/59761487/185657741-7f9427fd-6127-4e0d-b564-0d8a3cd6d1f8.png)

  
</details>

Additionally, the ultra importer glitches out and constantly switches between “1x” and “8x” in the RS controller (despite there only being 7 in the network), and it glitches out when scrolling as well. You can see what I mean in the video below. This also stops happening when I remove just one of the speed upgrades in the ultra importer, at which point it displays “7x” and everything works normally.

https://user-images.githubusercontent.com/59761487/185658088-06a0c0d9-20f6-4ab9-a8cb-6348f411cf3c.mp4

This is a very strange issue, and I actually have other ultra importers in the network, all with four speed upgrades, so it’s very strange that this only happened when connected to the multiservo press. It may be an issue with the interaction between Cable Tiers and Thermal Series in particular—or just that specific machine. I have no clue.

### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) (0.4.25)
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Cable Tiers:** 0.5461
* **Refined Storage:** 1.10.2

**Comment by DeleteMetaInf** [comment]
Exactly the same issue happened when I put an ultra exporter (with no speed upgrades) on an RFTools crafter. I don’t know what’s going on with these.

**Comment by starforcraft** [comment]
Can you try this with the newest Version Cable Tiers?

**Comment by DeleteMetaInf** [comment]
It turns out this was a power issue. My controller was apparently not getting enough energy, and the same issues I described started to happen even with regular Refined Storage importers and exporters with stack or speed upgrades. It makes sense that Cable Tiers’ advanced and ultra exporters and importers were doing this and that it happened with when I added speed upgrades because those all use more power.

I solved the issue by hooking up a better power source to my Refined Storage controller, at which point the freezing, crashing, and controller glitching stopped happening.

It’s still a very odd issue, and I don’t know why this even happened in the first place. Refined Storage must’ve been freaking out about not having as much power as it needed to run, so it caused the game all kinds of issues. My frame rate still drops from 75 fps to 44 fps when I open the grid, but I suppose there’s not much to do about that.

All in all, this is probably an issue with Refined Storage and not Cable Tiers.

**Comment by DeleteMetaInf** [comment]
I updated to the latest version, 0.547, but the same issue occurred. It turns out this was a power issue, though. My controller was apparently not getting enough energy, and the same issues I described started to happen even with regular Refined Storage importers and exporters with stack or speed upgrades. It makes sense that Cable Tiers’ advanced and ultra exporters and importers were doing this and that it happened with when I added speed upgrades because those all use more power.

I solved the issue by hooking up a better power source to my Refined Storage controller, at which point the freezing, crashing, and controller glitching stopped happening.

It’s still a very odd issue, and I don’t know why this even happened in the first place. Refined Storage must’ve been freaking out about not having as much power as it needed to run, so it caused the game all kinds of issues. My frame rate still drops from 75 fps to 44 fps when I open the grid, but I suppose there’s not much to do about that.

All in all, this is probably an issue with Refined Storage and not Cable Tiers.

**Comment by DeleteMetaInf** [comment]
Turns out this _is_ an issue with Refined Storage and can be solved by increasing the controller’s buffer in the server config. It’s been reported to the mod’s issue tracker [here](https://github.com/refinedmods/refinedstorage/issues/3350), but it doesn’t look like a fix is planned. This is something modpack developers should keep in mind, as the buffer should be increased, especially if the pack has Refined Storage add-ons like Cable Tiers.
