### ISSUE TITLE
[Suggestion] Add upgrade items

### ISSUE THREAD

**Issue by DeleteMetaInf** [starforcraft/Cable-Tiers#43]
I think it’d be fantastic if you could add upgrade items you can craft to upgrade an exporter, importer, constructor, destructor, disk manipulator, or requester to a higher tier. Say, upgrading a regular Refined Storage exporter to an ultra exporter or upgrading an elite requester to a creative requester, assuming it has a recipe in the modpack.

It’d save you a lot of time manually breaking each one and replacing them, and this can be a hassle if you have filters set up, as you have to redo the filters and all the options as well. With exporters, importers, or requesters with a lot of filters, it can take a long time to update them manually, especially if you have multiple, so having items you can craft for each tier to upgrade one to a higher tier would be incredibly handy!

You could add an upgrade item for each tier that works on all the blocks, or specific upgrade items for each type of block and each tier. And you’d probably have to make any speed or stack upgrades drop as well when upgrading, if the exporter, importer, requester, or disk manipulator of that tier doesn’t support a certain type of upgrade. All in all, I think it’d be a superb addition to the mod!

**Comment by starforcraft** [comment]
Same problem as https://github.com/starforcraft/Creative-Crafter/issues/10#issuecomment-1228226411
