### ISSUE TITLE
Cable tiers causing immense server side lag. ATM8 latest

### ISSUE THREAD

**Issue by Emikzen** [starforcraft/Cable-Tiers#51]
I'm not fully sure whats causing it but looking at the spark profile its something "VoxelShape". We're using cable tiers exporter/importers for a lot of things so cant safely say what exactly is causing it without breaking everything we built. 

Here's a ss of the log: 
![image](https://user-images.githubusercontent.com/50278938/235320454-974f0fd2-5c30-4c93-b290-85f7371397c1.png)

**Comment by Emikzen** [comment]
As an update, removing all covers seems to have solved it. But I'm not sure whether its refined storage or cable tiers causing it.

**Comment by starforcraft** [comment]
Its very likely a issue from Refined Storage because this mod uses the cover system from RS
