### ISSUE TITLE
Importers whitelist/blacklist mode broken

### ISSUE THREAD

**Issue by Hiattech** [starforcraft/Cable-Tiers#52]
Whitelist/blacklist mode do not work for importers. When setting items in whitelist mode, it pulls everything EXCEPT those in the whitelist. Clicking to change it to blacklist doesn't change it, instead it turns on redstone mode - requires redstone.
See my filter here: https://imgur.com/a/SfgVcRh
When I put these in the filter, it leaves those in the box and pulls everything else out.
I'm using this mod in ATM8 - 1.0.18

**Comment by starforcraft** [comment]
https://github.com/starforcraft/Cable-Tiers/issues/34
