### ISSUE TITLE
Had to disable Cable Tiers because it was breaking "Vanilla" RS Exporters/Importers

### ISSUE THREAD

**Issue by marco3102** [starforcraft/Cable-Tiers#53]
Dont really need this mod. All Gui was broken in the Advanced Exporters/Importers and in "Vanilla" RS too.
Only on my Server. RS Github says it got something to do with Desync.

**Comment by starforcraft** [comment]
Duplicate https://github.com/starforcraft/Cable-Tiers/issues/34

Btw to fix this issue Refined Storage has to change some code. I can’t do anything about it.
