### ISSUE TITLE
Requesters not working ATM8

### ISSUE THREAD

**Issue by GoldenRetrieverX** [starforcraft/Cable-Tiers#54]
As title states Requesters are not working in AllTheMods 8. I can hook up a regular Requestor from RSRequester mod and it works fine. If I plug in an  Elite, Ultra, or Creative Requester and open the interface it says 5000 in the amount to keep in storage. You are unable to change this 5000 and it will not 'request' anything. The example I'll show is crafting a water bucket (my pattern is mystical agriculture craft).

This image is of the requester just placed no changes - see how it is automatically set to 5000
![Empty Requester - Just placed - no change](https://github.com/starforcraft/Cable-Tiers/assets/123786258/1b2973f6-ad59-41a9-937f-52061b8d145a)

Next image I put a water bucket in and set to 10 to keep on hand
![Requester with Water bucket - set to 10](https://github.com/starforcraft/Cable-Tiers/assets/123786258/85cd8798-6580-4491-9367-a69ebfbf4e6f)

Close and re-opened interface > set back to 5000
![reverted requester](https://github.com/starforcraft/Cable-Tiers/assets/123786258/0c4e835a-d332-46e1-8ee4-120ffd1312d3)

Crafting monitor shows nothing being created even though requester has a bucket set to 5000 (since i cant set 10)
![nothing crafting](https://github.com/starforcraft/Cable-Tiers/assets/123786258/81aaf655-fe86-49a5-8d7c-9e794db76544)

Proving I have a water bucket craft available
![proof of water craft available and no water buckets](https://github.com/starforcraft/Cable-Tiers/assets/123786258/019824f9-d7d5-442e-b270-2951ff2e6fe0)

**Comment by starforcraft** [comment]
Duplicate https://github.com/starforcraft/Cable-Tiers/issues/34 (Backport not possible because it's a issue in old RS)
