### ISSUE TITLE
Selection of types and button functionality broken.

### ISSUE THREAD

**Issue by jkmmo69** [starforcraft/Cable-Tiers#55]
The Exporters / Importers/ Disk manipulators buttons on the ui do not work.

Importers and Exporters : issues  changing the types from items to fluids don't work when clicked.
Disk manipulators : issue clicking the buttons do nothing.

only changing the redstone mode works
[https://i.gyazo.com/86919de5152141346dc19e967b74029d.gif](url)

**Comment by starforcraft** [comment]
Duplicate https://github.com/starforcraft/Cable-Tiers/issues/34
