### ISSUE TITLE
Exporter NOT ignoring damaged items

### ISSUE THREAD

**Issue by datsme** [starforcraft/Cable-Tiers#56]
I am playing in ATM8 8-1.0.25. I am trying to clean out my storage by exporting enchanted items such as weapons, armor, etc into an Industrial Foregoing  Enchantment Extractor the enchanted books get piped into the Apotheosis Enchantment Library (via a hopper) then the unenchanted items go into a Silent Gear Salvager. Finally, the raw materials get imported back into storage. Everything works just fine with one exception. The Creative Exporter is NOT ignoring NBT/damaged info. so every item with different tags/damage has to manually be placed into the Exporter filter to work. The "Exact Mode" on the exporter looks as if its default is "Off" but it cannot be toggled to verify.

**Comment by starforcraft** [comment]
Caused by #34
