### ISSUE TITLE
Crafting Card does not works with Ultra Exporter

### ISSUE THREAD

**Issue by MSandro** [starforcraft/Cable-Tiers#57]
1.20.1
Forge 47.1.3
cabletiers-1.20.1-1.1.jar

**Comment by starforcraft** [comment]
It's integrated

**Comment by ThisisCanada98** [comment]
Looks like it does not seem to be the case in 1.19.2 as well

1.19.2
Forge 43.2.23

Exporting recipes that you have does not work with or without a crafting card

**Comment by D3rBay3r** [comment]
Playing ATM9 with Cable Tiers 1.20.1-1.2 and the exporters not crafting with or without crafting card

**Comment by starforcraft** [comment]
You have to update to 1.2.1
