### ISSUE TITLE
Elite Requester Recipe seems wrong

### ISSUE THREAD

**Issue by penturt** [starforcraft/Cable-Tiers#60]
not sure if i'm missing something, but the recipe for the Elite Requester only shows as an un-crafting recipe.

![2023-09-17_19 37 26](https://github.com/starforcraft/Cable-Tiers/assets/9455895/4f642ab8-c96f-4eb9-8b96-7b4b28bd70c5)

**Comment by penturt** [comment]
Adding image 

![2023-09-17_19 37 26](https://github.com/starforcraft/Cable-Tiers/assets/9455895/e8c0ee9c-bf52-4926-b277-1e1883ad93f1)

**Comment by starforcraft** [comment]
You have to install [rsrequestify ](https://www.curseforge.com/minecraft/mc-mods/rs-requestify)
