### ISSUE TITLE
Restore creative tier.

### ISSUE THREAD

**Issue by NJM1564** [starforcraft/Cable-Tiers#61]
I don't know why creative tier was removed, perhaps do to server lag or claims of OPness, but I play single player and was enjoying using them. Could you add them back. Even if they are disabled by default in the configs we could then at least turn them back on ourselves and pack makers could decide for themselves ether or not they want them.

**Comment by starforcraft** [comment]
Creative Tier got replaced by Mega Tier. Mega is a bit slower than Creative but still very fast and yeah it was removed due to sometimes massive server lags

**Comment by NJM1564** [comment]
Sigh. Fast but not nearly fast enough. Creative was the only thing in any mod short of a complicated Soryan level set up that could keep up with a Mechanism reactor.

**Comment by NJM1564** [comment]
Wouldn't a array of importers/exporters to try to produce the same results as one creative tier produce as mush or more lag as one of the creative tier?
