### ISSUE TITLE
Stack integrated addons craft and export ONLY stacks

### ISSUE THREAD

**Issue by J4YD3D** [starforcraft/Cable-Tiers#64]
Version 1.19.2-0.5471, In the ATM8 Modpack.
Tiered items that have an integrated stack upgrade will _only_ export in stacks, which is not the original Refined Storage function of the stack upgrade (It imports/exports in a stack, unless the item count is lower, then uses that number instead, eg: 24 items will come out at once). With the Creative exporter, and a crafting upgrade, the exporter will only craft if its able to create a stack or higher. The intended function of exporting a stack or the closest number still works if it already exists in the network, this is crafting ONLY issue.

**Comment by starforcraft** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/cable-tiers/files/4943107
