### ISSUE TITLE
Bug: Cable tiers is duplicating items

### ISSUE THREAD

**Issue by Kevin-Marsh** [starforcraft/Cable-Tiers#65]
Minecaft 1.20.1
Cable Tiers:  1.20.1-1.2.1
Refinedstorage: 1.12.4

It appears that Cable Tiers exporters are capable of duplicating items. It happens if you set an Exporter with fuzzy mode on to export an item with nbt such as a bundle with items in it and then place a second bundle in a chest with an external storage on it. This behavior is only present when an external storage is reading a storage and not when exporting items from a DISK.

[The user in this issue](https://github.com/AllTheMods/ATM-9/issues/1203#issuecomment-1936602789) made it easier by setting the duplication on the same chest in a loop but I also have duplicated the issue by setting up the exporter first, disconnecting it from the system so that it doesn't immediately try to export, placing the items and then connecting the cable.

![2024-02-10_08 12 59](https://github.com/starforcraft/Cable-Tiers/assets/9076964/21c38985-659a-4feb-879c-6682f9f7e684)

**Comment by starforcraft** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/cable-tiers/files/5104156
