### ISSUE TITLE
Importers

### ISSUE THREAD

**Issue by jacob0699** [starforcraft/Cable-Tiers#66]
When using importers from cable tiers, it wont import specific items. Using it as a way to get resources from my furnace into my refined system, it wont import diamonds, emeralds, lapis, coal, etc. but will import iron and gold. You cant change the redstone mode, tho that doesnt seem to matter if you dont want to control it, because its on redstone to activate but doesnt need restone to work. You cant change whitelist/blacklist mode, and you cant change item/fluid mode. I really like this mod as it keeps from needing 6 imports on an enderchest so it doesnt get clogged, but with these bugs it makes it hard to enjoy.

**Comment by starforcraft** [comment]
Version and log?

**Comment by starforcraft** [comment]
Closing this due to lack of feedback, feel free to open it again
